vich_uploader:
    db_driver: orm
    mappings:
        post_images:
            uri_prefix: /uploads/post
            upload_destination: '%kernel.project_dir%/public/uploads/post'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        video_files:
            uri_prefix: /uploads/post/videos
            upload_destination: '%kernel.project_dir%/public/uploads/post/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        ebook_files:
            uri_prefix: /uploads/ebook
            upload_destination: '%kernel.project_dir%/public/uploads/ebook'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
