vich_uploader:
    db_driver: orm

    mappings:
       ebook_files:
        uri_prefix: /uploads/ebook
        upload_destination: '%kernel.project_dir%/public/uploads/ebook'
          
       image_upload:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
