vich_uploader:
    db_driver: orm

    mappings:
       ebook_files:
           uri_prefix: 'public/img/ebooks'
           upload_destination: '%kernel.project_dir%/public/img/ebooks'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
