vich_uploader:
    db_driver: orm
    mappings:
        video_files:
            uri_prefix: /uploads/videos
            upload_destination: '%kernel.project_dir%/public/uploads/post/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        ebook_aperçu:
            uri_prefix: /uploads/ebook/apercu
            upload_destination: '%kernel.project_dir%/public/uploads/ebook/apercu'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        ebook_pdf:
            uri_prefix: /uploads/ebook/pdf
            upload_destination: '%kernel.project_dir%/public/uploads/ebook/pdf'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        page_images: # The mapping name you used in the "Vich\UploadableField" annotation
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/page/'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        images: # The mapping name you used in the "Vich\UploadableField" annotation
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/images/'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            
        
