vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /video/images
           upload_destination: '%kernel.project_dir%/public/img/uploads'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
