vich_uploader:
    db_driver: orm

    metadata: 
        type: attribute

    mappings:
        ebook_files:
            uri_prefix: /uploads/ebook
            upload_destination: '%kernel.project_dir%/public/uploads/ebook'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
          
        image_upload:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        video_files :
            upload_destination: '%kernel.project_dir%/public/uploads/post/videos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        post_images :
            upload_destination: '%kernel.project_dir%/public/uploads/post/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

