# config/routes/easy_admin.yaml

easy_admin_bundle:
    controller: App\Controller\Admin\DashboardController
    path: /admin
    prefix: /admin

# change_roles:
#     path: /admin/user/{id}/change-roles
#     controller: App\Controller\Admin\UserController::changeRoles
