controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: annotation
    prefix:
        /: "/"
        fr: "/fr"
        en: "/en"
    locale: ""
    defaults:
        _locale: "fr"
    requirements:
        _locale: "fr|en"
    trailing_slash_on_root: true

kernel:
    resource: App\Kernel
    type: attribute

# routes.yaml
# app_security:
#     resource: App\Controller\SecurityController
#     type: annotation

# app_register:
#     path: /new-account
#     controller: App\Controller\RegistrationController::register
#     methods: [GET, POST]

# app_verify_email:
#     path: /verify/email
#     controller: App\Controller\RegistrationController::verifyUserEmail
#     methods: [GET]








