zzcontrollers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: annotation
    prefix:
        /: "/"
        fr: "/fr"
        en: "/en"
    locale: ""
    defaults:
        _locale: "fr"
    requirements:
        _locale: "fr|en"
    trailing_slash_on_root: true

kernel:
    resource: App\Kernel
    type: attribute

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix:   /_error

